version: '2'

services:
  s3fs:
    image: anthonymag/s3fs-httpd:latest
    environment:
      AWSACCESSKEYID: FOOBAR
      AWSSECRETACCESSKEY: FOOBARBAZ
    cap_add:
      - MKNOD
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse
    volumes:
      - /var/lib/S3_BUCKET_NAME:/usr/local/apache2/htdocs/:shared
    command: /usr/bin/s3fs -f -o allow_other -o use_cache=/tmp S3_BUCKET_NAME /usr/local/apache2/htdocs/
